spring:
  application:
    name: platform-service-b
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 3dd14094-6c67-45f2-a378-794e2f9cd19b


server:
  port: 9091
  servlet:
    context-path: /
ribbon:
  eager-load:
    #开启饥饿加载
    enabled: true
    #为哪些服务的名称开启饥饿加载,多个用逗号分隔
    clients: platform-service-a

dubbo:
  scan:
    # dubbo 服务扫描基准包,注意不是api包，是有@service注解的包
    base-packages: com.tdt.platform.serviceb.service
  protocol:
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    # 订阅服务，不写会提示订阅了所有，如果只是生产者，此处空者，订阅多个服务用,分隔
    subscribed-services: platform-service-a
  consumer:
    check: false