server:
  port: 8000
spring:
  application:
    name: cloud-gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: product_route
            # uri: http://localhost:9002
          uri: lb://cloud-product-service
          predicates:
          - Path=/cloud-product-service/**
          # UTC时间格式
          - After=2013-01-20T17:42:47.789-07:00[America/Denver]
          - Age=18,65

          filters:
            - StripPrefix=1
            - MyLog=true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
logging:
  level:


    root: debug
