server:
  port: 8020

spring:
  application:
    name: platform-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 需要在nacos创建一个命名空间（uuid）
        namespace: 3dd14094-6c67-45f2-a378-794e2f9cd19b
    gateway:
      routes:
      - id: platform-service-a
        uri: lb://platform-service-a
        predicates:
        - Path=/**
      - id: platform-service-b
        uri: lb://platform-service-b
        predicates:
        - Path=/**

      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always