spring:
  application:
    name: platform-service-b
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 3dd14094-6c67-45f2-a378-794e2f9cd19b
    sentinel:
      transport:
        # 指定sentinel控制台地址
        dashboard: localhost:8080
        # 指定和控制台通信的IP，若不配置，会自动选择一个IP注册
        client-ip: 127.0.0.1
        # 指定和控制台通信的端口哦，默认值8719
        # 若不配置，会自动扫猫从8719开始扫猫，依次+1，知道值找到未被占用的端口
        #port: 8719
        # 心跳发送周期，默认值null
        # 但在SimpleHttpHeartbeatSender会用默认值10秒
        heartbeat-interval-ms: 10000


server:
  port: 9091
  servlet:
    context-path: /
ribbon:
  eager-load:
    #开启饥饿加载
    enabled: true
    #为哪些服务的名称开启饥饿加载,多个用逗号分隔
    clients: platform-service-a

dubbo:
  scan:
    # dubbo 服务扫描基准包,注意不是api包，是有@service注解的包
    base-packages: com.tdt.platform.serviceb.service
  protocol:
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    # 订阅服务，不写会提示订阅了所有，如果只是生产者，此处空者，订阅多个服务用,分隔
    subscribed-services: platform-service-a
  consumer:
    check: false